[tools]
"cargo:hexview" = "latest"
"npm:@webos-tools/cli" = "latest"
"pipx:aws-encryption-sdk-cli" = "latest"
"pipx:toolong" = "latest"

[settings]
experimental = true

[settings.python]
compile = false
