"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Stuart Hicks"
email = "stuarthicks@users.noreply.github.com"

[git]
subprocess = true

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ2odgEamTZm8fkbCwsAmsCQFTz8P/l06yJpniahH4wW"

[signing.backends.ssh]
allowed-signers = "~/.ssh/allowed_signers"

[ui]
default-command = "log"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
show-cryptographic-signatures = true

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
    "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
    "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true

[revset-aliases]
'bough(x, m)' = 'descendants(ancestors(x) ~ ancestors(m))'
'bough(x)' = 'bough(x, trunk())'
'bough' = 'bough(@)'
